import { Activity, DayPlan, UserTrip } from '../models';

/**
 * Demo trip dataset.
 *
 * This is the single source of truth for trips while the app runs without a
 * backend. `TripService` reads from here; swap it for HTTP calls later without
 * touching any component. Activity ids are generated by {@link buildTrip} so the
 * literals below stay readable and ids are guaranteed unique per trip.
 */

type RawActivity = Omit<Activity, 'id'>;
type RawDay = Omit<DayPlan, 'activities'> & { activities: RawActivity[] };
type RawTrip = Omit<UserTrip, 'days'> & { days: RawDay[] };

function buildTrip(raw: RawTrip): UserTrip {
  return {
    ...raw,
    days: raw.days.map((day) => ({
      ...day,
      activities: day.activities.map((activity, index) => ({
        ...activity,
        id: `${raw.id}-d${day.dayNumber}-a${index + 1}`,
      })),
    })),
  };
}

const PARIS: RawTrip = {
  id: 'trip-1',
  destination: 'Paris',
  country: 'France',
  from: 'Cairo',
  coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80',
  departureDate: '2026-07-15',
  returnDate: '2026-07-18',
  totalBudget: 5000,
  spentBudget: 3200,
  travelStyle: ['cultural', 'foodie'],
  status: 'upcoming',
  flight: {
    airline: 'Air France',
    flightNumber: 'AF 571',
    departure: 'Cairo (CAI)',
    arrival: 'Paris Charles de Gaulle (CDG)',
    departureTime: '09:10',
    arrivalTime: '13:05',
  },
  hotel: {
    name: 'Hôtel Le Marais',
    address: 'Rue de Rivoli 18, Paris',
    stars: 4,
    checkIn: 'July 15',
    checkOut: 'July 18',
    rating: 8.9,
  },
  days: [
    {
      dayNumber: 1,
      date: 'July 15 — Wednesday',
      title: 'Icons of the Left Bank',
      weather: {
        date: 'July 15',
        tempMax: 26,
        tempMin: 16,
        condition: 'Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'Clear skies all day — ideal for the Eiffel Tower at golden hour. Book lift tickets ahead to skip the queue.',
      },
      activities: [
        { time: '10:00 AM', title: 'Eiffel Tower', locationName: 'Eiffel Tower', lat: 48.8584, lng: 2.2945, description: 'Ascend the Iron Lady. Reserve summit access in advance for the best Paris panorama.', type: 'sightseeing', category: 'attraction', icon: '🗼' },
        { time: '01:00 PM', title: 'Lunch at Café Constant', locationName: 'Café Constant', lat: 48.8589, lng: 2.3045, description: 'Cosy bistro near the tower. Try the duck confit and crème brûlée.', type: 'food', category: 'food', icon: '🍽️' },
        { time: '03:00 PM', title: 'Musée d\'Orsay', locationName: 'Musée d\'Orsay', lat: 48.86, lng: 2.3266, description: 'Impressionist masterpieces in a former railway station. Don\'t miss Monet and Van Gogh.', type: 'sightseeing', category: 'attraction', icon: '🖼️' },
        { time: '07:30 PM', title: 'Seine River Dinner Cruise', locationName: 'Seine River Cruise', lat: 48.86, lng: 2.305, description: 'Glide past illuminated landmarks with a three-course dinner aboard.', type: 'activity', category: 'leisure', icon: '🚤' },
      ],
    },
    {
      dayNumber: 2,
      date: 'July 16 — Thursday',
      title: 'Art, History & the Marais',
      weather: {
        date: 'July 16',
        tempMax: 24,
        tempMin: 15,
        condition: 'Partly Cloudy',
        iconUrl: 'https://openweathermap.org/img/wn/02d@2x.png',
        aiTip: 'Comfortable and breezy. Perfect for wandering the Marais on foot — wear good walking shoes.',
      },
      activities: [
        { time: '09:30 AM', title: 'The Louvre', locationName: 'Louvre Museum', lat: 48.8606, lng: 2.3376, description: 'The world\'s largest art museum. Head straight for the Mona Lisa, then explore at your own pace.', type: 'sightseeing', category: 'attraction', icon: '🏛️' },
        { time: '12:30 PM', title: 'Lunch in Le Marais', locationName: 'Le Marais', lat: 48.859, lng: 2.358, description: 'Famous falafel and chic cafés in Paris\'s most charming historic quarter.', type: 'food', category: 'food', icon: '🥙' },
        { time: '02:30 PM', title: 'Notre-Dame & Île de la Cité', locationName: 'Notre-Dame Cathedral', lat: 48.853, lng: 2.3499, description: 'Admire the Gothic façade and stroll the medieval island at the heart of Paris.', type: 'sightseeing', category: 'attraction', icon: '⛪' },
        { time: '08:00 PM', title: 'Dinner in the Latin Quarter', locationName: 'Latin Quarter', lat: 48.8499, lng: 2.3471, description: 'Lively student district packed with bistros, wine bars and live music.', type: 'food', category: 'food', icon: '🍷' },
      ],
    },
    {
      dayNumber: 3,
      date: 'July 17 — Friday',
      title: 'Montmartre & Grand Boulevards',
      weather: {
        date: 'July 17',
        tempMax: 23,
        tempMin: 14,
        condition: 'Light Rain',
        iconUrl: 'https://openweathermap.org/img/wn/10d@2x.png',
        aiTip: 'Pack a light umbrella for morning showers — they clear by midday, leaving soft light for Montmartre.',
      },
      activities: [
        { time: '10:00 AM', title: 'Sacré-Cœur & Montmartre', locationName: 'Basilica of Sacré-Cœur', lat: 48.8867, lng: 2.3431, description: 'Hilltop basilica with sweeping city views. Watch artists at work on Place du Tertre.', type: 'sightseeing', category: 'attraction', icon: '⛪' },
        { time: '01:00 PM', title: 'Lunch at La Maison Rose', locationName: 'La Maison Rose', lat: 48.8887, lng: 2.3401, description: 'The famously photogenic pink café in the heart of Montmartre.', type: 'food', category: 'food', icon: '🌹' },
        { time: '03:30 PM', title: 'Champs-Élysées & Arc de Triomphe', locationName: 'Arc de Triomphe', lat: 48.8738, lng: 2.295, description: 'Walk the grand avenue and climb the arch for a star-shaped view of twelve boulevards.', type: 'sightseeing', category: 'attraction', icon: '🏛️' },
        { time: '07:00 PM', title: 'Farewell Dinner at Le Train Bleu', locationName: 'Le Train Bleu', lat: 48.8443, lng: 2.3743, description: 'Opulent Belle Époque restaurant inside Gare de Lyon — a memorable send-off.', type: 'food', category: 'food', icon: '🎉' },
      ],
    },
  ],
};

const DUBAI: RawTrip = {
  id: 'trip-2',
  destination: 'Dubai',
  country: 'United Arab Emirates',
  from: 'Cairo',
  coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
  departureDate: '2026-06-01',
  returnDate: '2026-06-04',
  totalBudget: 8000,
  spentBudget: 7500,
  travelStyle: ['luxury', 'adventure'],
  status: 'completed',
  flight: {
    airline: 'Emirates',
    flightNumber: 'EK 924',
    departure: 'Cairo (CAI)',
    arrival: 'Dubai International (DXB)',
    departureTime: '15:40',
    arrivalTime: '20:55',
  },
  hotel: {
    name: 'Atlantis, The Palm',
    address: 'Crescent Rd, Palm Jumeirah, Dubai',
    stars: 5,
    checkIn: 'June 1',
    checkOut: 'June 4',
    rating: 9.4,
  },
  days: [
    {
      dayNumber: 1,
      date: 'June 1 — Monday',
      title: 'Downtown & the Burj Khalifa',
      weather: {
        date: 'June 1',
        tempMax: 41,
        tempMin: 30,
        condition: 'Hot & Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'Extreme heat midday — plan indoor, air-conditioned stops between noon and 4 PM and hydrate constantly.',
      },
      activities: [
        { time: '11:00 AM', title: 'The Dubai Mall', locationName: 'The Dubai Mall', lat: 25.1985, lng: 55.2796, description: 'One of the world\'s largest malls — aquarium, ice rink and endless boutiques to beat the heat.', type: 'activity', category: 'leisure', icon: '🛍️' },
        { time: '02:00 PM', title: 'Lunch at At.mosphere', locationName: 'At.mosphere, Burj Khalifa', lat: 25.1972, lng: 55.2744, description: 'Fine dining on the 122nd floor of the Burj Khalifa with cloud-level views.', type: 'food', category: 'food', icon: '🍽️' },
        { time: '05:00 PM', title: 'Burj Khalifa — At the Top', locationName: 'Burj Khalifa', lat: 25.1972, lng: 55.2744, description: 'Ride to the observation deck of the tallest building on Earth for sunset.', type: 'sightseeing', category: 'attraction', icon: '🏙️' },
        { time: '08:00 PM', title: 'The Dubai Fountain Show', locationName: 'The Dubai Fountain', lat: 25.1955, lng: 55.2754, description: 'Choreographed water, light and music on the Burj Lake every 30 minutes.', type: 'activity', category: 'leisure', icon: '⛲' },
      ],
    },
    {
      dayNumber: 2,
      date: 'June 2 — Tuesday',
      title: 'Desert Adventure',
      weather: {
        date: 'June 2',
        tempMax: 43,
        tempMin: 31,
        condition: 'Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'Save the desert safari for late afternoon when dunes cool. Bring a scarf for blowing sand.',
      },
      activities: [
        { time: '10:00 AM', title: 'Jumeirah Beach Morning', locationName: 'Jumeirah Public Beach', lat: 25.2048, lng: 55.2401, description: 'Relax on white sand with the Burj Al Arab as your backdrop before the heat peaks.', type: 'activity', category: 'leisure', icon: '🏖️' },
        { time: '01:00 PM', title: 'Lunch at Madinat Jumeirah', locationName: 'Souk Madinat Jumeirah', lat: 25.133, lng: 55.185, description: 'Waterfront dining in a recreated Arabian souk with abra canals.', type: 'food', category: 'food', icon: '🛶' },
        { time: '04:00 PM', title: 'Red Dune Desert Safari', locationName: 'Dubai Desert Conservation Reserve', lat: 24.9216, lng: 55.5, description: 'Dune bashing, camel rides and sandboarding in the golden desert.', type: 'activity', category: 'leisure', icon: '🐫' },
        { time: '07:30 PM', title: 'Bedouin Camp Dinner', locationName: 'Desert Camp', lat: 24.93, lng: 55.51, description: 'BBQ feast under the stars with live tanoura dancing and shisha.', type: 'food', category: 'food', icon: '🔥' },
      ],
    },
    {
      dayNumber: 3,
      date: 'June 3 — Wednesday',
      title: 'The Palm & Marina',
      weather: {
        date: 'June 3',
        tempMax: 42,
        tempMin: 31,
        condition: 'Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'A great day for the water park — book Aquaventure early to claim shade before crowds arrive.',
      },
      activities: [
        { time: '10:30 AM', title: 'Aquaventure Waterpark', locationName: 'Atlantis Aquaventure', lat: 25.1304, lng: 55.1171, description: 'Record-breaking slides and a shark-filled lagoon on Palm Jumeirah.', type: 'activity', category: 'leisure', icon: '🌊' },
        { time: '02:00 PM', title: 'Lunch at Pierchic', locationName: 'Pierchic', lat: 25.1342, lng: 55.1844, description: 'Overwater seafood restaurant on a pier with Burj Al Arab views.', type: 'food', category: 'food', icon: '🦞' },
        { time: '05:00 PM', title: 'Dubai Marina Walk', locationName: 'Dubai Marina', lat: 25.0805, lng: 55.1403, description: 'Stroll the glittering waterfront promenade lined with yachts and cafés.', type: 'sightseeing', category: 'attraction', icon: '🛥️' },
        { time: '08:00 PM', title: 'Farewell Dinner at Pier 7', locationName: 'Pier 7', lat: 25.0772, lng: 55.1393, description: 'Seven restaurants stacked over the marina — end the trip with skyline views.', type: 'food', category: 'food', icon: '🎉' },
      ],
    },
  ],
};

const ROME: RawTrip = {
  id: 'trip-3',
  destination: 'Rome',
  country: 'Italy',
  from: 'Cairo',
  coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80',
  departureDate: '2026-08-10',
  returnDate: '2026-08-13',
  totalBudget: 6000,
  spentBudget: 0,
  travelStyle: ['cultural', 'foodie', 'nature'],
  status: 'upcoming',
  flight: {
    airline: 'ITA Airways',
    flightNumber: 'AZ 204',
    departure: 'Cairo (CAI)',
    arrival: 'Rome Fiumicino (FCO)',
    departureTime: '08:30',
    arrivalTime: '11:15',
  },
  hotel: {
    name: 'Hotel Artemide',
    address: 'Via Nazionale 22, Rome',
    stars: 5,
    checkIn: 'August 10',
    checkOut: 'August 13',
    rating: 9.2,
  },
  days: [
    {
      dayNumber: 1,
      date: 'August 10 — Monday',
      title: 'Arrival & Ancient Rome',
      weather: {
        date: 'August 10',
        tempMax: 31,
        tempMin: 22,
        condition: 'Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'Perfect sunny day! Apply SPF 50+ and carry a water bottle — Colosseum visits can be intense under direct sunlight.',
      },
      activities: [
        { time: '09:00 AM', title: 'Hotel Artemide — Check-in & Breakfast', locationName: 'Hotel Artemide', lat: 41.8985, lng: 12.4994, description: 'Settle in and enjoy a lavish Italian breakfast at the hotel rooftop café.', type: 'hotel', category: 'hotel', icon: '🏨' },
        { time: '11:00 AM', title: 'Colosseum', locationName: 'Colosseum', lat: 41.8902, lng: 12.4922, description: 'Explore the iconic Flavian Amphitheatre. Book skip-the-line tickets in advance. Arena floor access highly recommended.', type: 'sightseeing', category: 'attraction', icon: '🏛️' },
        { time: '01:30 PM', title: 'Lunch at Hostaria Romana', locationName: 'Hostaria Romana', lat: 41.9018, lng: 12.481, description: 'Classic Roman trattoria near the Trevi Fountain. Try Cacio e Pepe and Supplì.', type: 'food', category: 'food', icon: '🍝' },
        { time: '03:00 PM', title: 'Palatine Hill & Roman Forum', locationName: 'Palatine Hill & Roman Forum', lat: 41.8894, lng: 12.4872, description: 'Wander through the ancient heart of the Roman Empire. Panoramic views of the Forum are unmissable.', type: 'sightseeing', category: 'attraction', icon: '🏺' },
        { time: '06:00 PM', title: 'Trevi Fountain', locationName: 'Trevi Fountain', lat: 41.9009, lng: 12.4833, description: 'Toss a coin and make your wish! Visit at sunset for the best golden-hour photos.', type: 'activity', category: 'leisure', icon: '⛲' },
        { time: '08:30 PM', title: 'Dinner at Il Sorpasso', locationName: 'Il Sorpasso', lat: 41.9026, lng: 12.4657, description: 'Trendy Roman bar-restaurant in Prati. Order the wine board and Roman-style pizza.', type: 'food', category: 'food', icon: '🍷' },
      ],
    },
    {
      dayNumber: 2,
      date: 'August 11 — Tuesday',
      title: 'Vatican City & Papal Rome',
      weather: {
        date: 'August 11',
        tempMax: 28,
        tempMin: 19,
        condition: 'Partly Cloudy',
        iconUrl: 'https://openweathermap.org/img/wn/02d@2x.png',
        aiTip: 'Light clouds will keep temperatures comfortable. Great day for Vatican City — expect crowds. Arrive early!',
      },
      activities: [
        { time: '08:00 AM', title: 'Breakfast at Caffè San Pietro', locationName: 'Caffè San Pietro', lat: 41.9012, lng: 12.4573, description: 'Classic Italian cornetto and espresso just steps from Vatican City.', type: 'food', category: 'food', icon: '☕' },
        { time: '09:30 AM', title: 'Vatican Museums & Sistine Chapel', locationName: 'Vatican Museums & Sistine Chapel', lat: 41.9065, lng: 12.4536, description: 'Marvel at Michelangelo\'s breathtaking ceiling. The Gallery of Maps and Raphael Rooms are not to be missed.', type: 'sightseeing', category: 'attraction', icon: '🎨' },
        { time: '12:30 PM', title: 'St. Peter\'s Basilica', locationName: 'St. Peter\'s Basilica', lat: 41.9022, lng: 12.4539, description: 'Climb the dome for panoramic Rome views. Free entry to the Basilica — dress code enforced (cover shoulders & knees).', type: 'sightseeing', category: 'attraction', icon: '⛪' },
        { time: '02:30 PM', title: 'Lunch at Settimio all\'Arancio', locationName: 'Ristorante Settimio all\'Arancio', lat: 41.9008, lng: 12.4776, description: 'Authentic Roman cuisine in a charming side street. Try the Artichoke alla Romana.', type: 'food', category: 'food', icon: '🥗' },
        { time: '04:00 PM', title: 'Castel Sant\'Angelo', locationName: 'Castel Sant\'Angelo', lat: 41.9031, lng: 12.4663, description: 'The ancient mausoleum turned papal fortress. The terrace offers one of the best views of the Tiber River.', type: 'sightseeing', category: 'attraction', icon: '🏰' },
        { time: '07:30 PM', title: 'Dinner in the Pigneto District', locationName: 'Pigneto District', lat: 41.8867, lng: 12.5388, description: 'Trendy bohemian neighborhood. Bar-hopping and street food for a local Roman evening experience.', type: 'food', category: 'food', icon: '🌆' },
      ],
    },
    {
      dayNumber: 3,
      date: 'August 12 — Wednesday',
      title: 'Art, Culture & Trastevere',
      weather: {
        date: 'August 12',
        tempMax: 26,
        tempMin: 17,
        condition: 'Light Rain',
        iconUrl: 'https://openweathermap.org/img/wn/10d@2x.png',
        aiTip: 'Pack a compact umbrella! Morning showers expected. Perfect day to explore indoor museums and covered piazzas.',
      },
      activities: [
        { time: '09:30 AM', title: 'Borghese Gallery', locationName: 'Borghese Gallery', lat: 41.9142, lng: 12.4921, description: 'One of the world\'s finest small museums. Home to Bernini\'s Apollo and Daphne — book tickets weeks in advance.', type: 'sightseeing', category: 'attraction', icon: '🖼️' },
        { time: '12:00 PM', title: 'Lunch at Nino Ristorante', locationName: 'Nino Ristorante', lat: 41.9053, lng: 12.4813, description: 'A Florentine institution in Rome. Outstanding Bistecca alla Fiorentina.', type: 'food', category: 'food', icon: '🥩' },
        { time: '02:00 PM', title: 'Pantheon', locationName: 'Pantheon', lat: 41.8986, lng: 12.4769, description: 'The best-preserved ancient Roman temple. The oculus is a jaw-dropping architectural marvel.', type: 'sightseeing', category: 'attraction', icon: '🔵' },
        { time: '03:30 PM', title: 'Piazza Navona', locationName: 'Piazza Navona', lat: 41.8992, lng: 12.4731, description: 'Baroque Rome at its finest. Bernini\'s Fountain of the Four Rivers dominates this magnificent square.', type: 'activity', category: 'leisure', icon: '🎭' },
        { time: '05:30 PM', title: 'Aperitivo at Salotto 42', locationName: 'Salotto 42', lat: 41.8985, lng: 12.4772, description: 'A stylish bar overlooking the Pantheon. Perfect spot for Aperol Spritz and light bites.', type: 'activity', category: 'leisure', icon: '🍸' },
        { time: '08:00 PM', title: 'Dinner at Glass Hostaria — Trastevere', locationName: 'Glass Hostaria', lat: 41.8889, lng: 12.4696, description: 'Michelin-starred modern Roman cuisine in charming Trastevere. Reserve in advance.', type: 'food', category: 'food', icon: '⭐' },
      ],
    },
    {
      dayNumber: 4,
      date: 'August 13 — Thursday',
      title: 'Local Life & Farewell',
      weather: {
        date: 'August 13',
        tempMax: 33,
        tempMin: 24,
        condition: 'Hot & Sunny',
        iconUrl: 'https://openweathermap.org/img/wn/01d@2x.png',
        aiTip: 'Hottest day of the trip! Consider visiting the Appian Way early morning and seek shade at Testaccio market midday.',
      },
      activities: [
        { time: '08:00 AM', title: 'Morning Jog — Villa Borghese Gardens', locationName: 'Villa Borghese Gardens', lat: 41.9133, lng: 12.4887, description: 'Start the day with a refreshing jog through Rome\'s central park. Rent a bike at the park entrance.', type: 'activity', category: 'leisure', icon: '🚲' },
        { time: '10:00 AM', title: 'Testaccio Market', locationName: 'Testaccio Market', lat: 41.8797, lng: 12.4784, description: 'Rome\'s best covered food market. Sample supplì, cacio e pepe cones, and artisan cheeses.', type: 'food', category: 'food', icon: '🛒' },
        { time: '12:30 PM', title: 'Appian Way (Via Appia Antica)', locationName: 'Appian Way', lat: 41.8575, lng: 12.5114, description: 'One of the most romantic ancient roads in the world. Rent a bicycle and ride through history.', type: 'sightseeing', category: 'attraction', icon: '🛣️' },
        { time: '03:00 PM', title: 'Catacombe di San Callisto', locationName: 'Catacombe di San Callisto', lat: 41.8594, lng: 12.515, description: 'Descend into the underground burial grounds of early Christians. Guided tours in multiple languages.', type: 'sightseeing', category: 'attraction', icon: '⚰️' },
        { time: '05:30 PM', title: 'Trastevere Neighborhood Walk', locationName: 'Trastevere', lat: 41.8895, lng: 12.4699, description: 'Stroll through the most romantic neighborhood in Rome. Golden evening light makes this magical.', type: 'activity', category: 'leisure', icon: '🌅' },
        { time: '08:00 PM', title: 'Farewell Dinner at Da Enzo al 29', locationName: 'Da Enzo al 29', lat: 41.889, lng: 12.472, description: 'The quintessential Roman trattoria experience. Try the Cacio e Pepe and end with Tiramisù.', type: 'food', category: 'food', icon: '🎉' },
      ],
    },
  ],
};

/** All demo trips, with generated activity ids. */
export const MOCK_TRIPS: UserTrip[] = [PARIS, DUBAI, ROME].map(buildTrip);
